### ISSUE TITLE
多次元のプロット関数

### ISSUE THREAD

**Issue by tkrhsn** [issp-center-dev/PHYSBO#22]
多次元でのガウス過程回帰を用いた実験計画法を実施したいのですが、フィッティングしたガウス過程回帰と獲得関数を２次元サーフェスプロットで表示する機能はないでしょうか？

**Comment by yomichi** [comment]
現状、描画機能はありません。
開発チームとしてではなく個人の意見ですが、可視化に関してはライブラリの選択や、色などのパラメータの選択など、個々人の好みに依る部分が大きいと思いますので、ご自身でやられるのが一番だと思っています。
(PHYSBO の場合は、入力として等間隔なグリッドを仮定していないというのもあります。 ざっと見る目的として散布図を出力する程度の機能なら可能かもしれませんが、実装するかはわかりません)

ガウス過程回帰の結果および獲得関数の値は
`policy.get_post_fmean(xs=X)` ないし `policy.get_score(xs=X)` で取得可能です。

**Comment by tkrhsn** [comment]
承知致しました。ありがとうございました。
