### ISSUE TITLE
獲得関数TSでのget_scoreの戻り値

### ISSUE THREAD

**Issue by tkrhsn** [issp-center-dev/PHYSBO#23]
獲得関数がEIやPIのときは戻り値が一重のリストですが、TSのときは二重のリストで戻ってきます。どちらかに統一してもらえないでしょうか？

EI, PIの場合
[2.90841329e-204 ... 3.72840278e-189]

TSの場合
[[-3.21928677 ... -4.84607939]]

**Comment by yomichi** [comment]
まだリリースしていませんが、最新版 (develop branch) では修正済みです。
さしあたっては `flatten()` を使うと吸収できるかと思います
