### ISSUE TITLE
新たな獲得関数

### ISSUE THREAD

**Issue by tkrhsn** [issp-center-dev/PHYSBO#24]
UCBやMIといった獲得関数の実装予定はありますでしょうか？

**Comment by yomichi** [comment]
予定があるかと言われると、未定です。
（私見ですが）期待値とそれ以外の項との重みを調整するハイパーパラメータを導入しないといけないのが面倒な気もちょっとしています。
まぁ、それを試す意味も含めていろいろな選択肢を比較するのはいいでしょうし、検討しておきます。

**Comment by tkrhsn** [comment]
ぜひ検討していただければ幸いです。
