### ISSUE TITLE
kernelの指定

### ISSUE THREAD

**Issue by tkrhsn** [issp-center-dev/PHYSBO#25]
kernelの指定はできますでしょうか？

**Comment by yomichi** [comment]
現状としてはいわゆるガウスカーネルのみです。

**Comment by tkrhsn** [comment]
承知致しました。他カーネルの実装予定はありますか？

**Comment by yomichi** [comment]
獲得関数同様、予定があるかどうかと言われたらありません。

PHYSBO （およびCOMBO） の場合、ガウス過程回帰そのものだけではなく、（ガウス）カーネルを（期待値的な意味で）生成するような基底関数の組による、双対なベイズ線形モデルを用いた回帰に変形することで、データ数に対してスケーリングするような機能をつけているため、ガウスカーネル以外に拡張する向きには行きづらいと思っています。
（もちろん、やらないことの強い理由にはなっていないので、予定として全くのゼロではないです）
