### ISSUE TITLE
initial_data指定時のsimulator実行失敗

### ISSUE THREAD

**Issue by rarai01** [issp-center-dev/PHYSBO#32]
PHYSBO V.1.0.1

 physbo.search.discrete.policyでinitial_dataを指定した際、policy.random_searchでsimulatorを用いると下記エラーが発生します。
TypeError: only integer scalar arrays can be converted to a scalar index

通常、ndarray型のpolicy.actionsがlist型になっており、policy.actionsをndarrayにキャストするとエラーが回避できました。
ソースを確認したところ、policy.__init__が原因であると思われます。
ご確認のほどよろしくお願いいたします。

<details>
  <summary>Code</summary>
 
```
import physbo
import numpy as np

def load_data():
    A =  np.asarray(np.loadtxt('./example.csv',skiprows=1, delimiter=',') )
    X = A[:,0:3]
    t  = -A[:,3]
    return X, t

X, t = load_data()
X = physbo.misc.centering(X)

class simulator:
    def __init__(self, t):
        self.t = t
    
    def __call__(self, action):
        return -self.t[action]

import random
random.seed(0)
calculated_ids = random.sample(range(t.size), 20)
t_initial = t[calculated_ids]

policy = physbo.search.discrete.policy(test_X=X, initial_data=[calculated_ids, t_initial])
actions = policy.random_search(max_num_probes=10, simulator=simulator(t))
```
 
</details>

**Comment by yomichi** [comment]
ご報告、どうもありがとうございます、遅くなって申し訳ありません。
修正しました (#34, develop branch)。
他の微修正と合わせて 1.0.2 を早めに出します。
