### ISSUE TITLE
ファイルからロードした後に新しい結果を書き込めない

### ISSUE THREAD

**Issue by k-kitai** [issp-center-dev/PHYSBO#52]
`history`クラスの内容を`save`メソッドでnpzファイルに保存しておいたものを`load`メソッドで読み込み、複数のアクションの結果を書き込もうとするとエラーになります。再現コードは以下のとおりです。
```
from physbo.search.discrete import history
his = history()
his.write(t=[3.14], action=[0])
his.save("history.npz")
his.load("history.npz")
his.write(t=[2.18, 1.618], action=[1, 2]) # ValueError: could not broadcast input array from shape (2,) into shape (0,)
```
原因は`history`クラスの`int`型のインスタンス変数である`num_runs`と`total_num_search` が、npzファイルに保存した際に`numpy.ndarray`型に変化してしまい、その値を別の変数に格納するときに参照渡しになっているからのようです。`load`メソッドでこれらの値を読み出した時に、キャストで明示的に`int`型に戻してはいかがでしょうか。

**Comment by k-yoshimi** [comment]
@k-kitai 
バグ報告と解決方法のご提案をありがとうございます。
修正対応後にIssueにその旨を記載するようにします。

**Comment by yomichi** [comment]
@k-kitai 
すみません、大変遅くなりましたが修正しました。(#59)
develop ブランチにありますが、他の修正と合わせてなるべく早く新しいバージョンを出します

**Comment by yomichi** [comment]
2024/8に出したv2.0.1に入っているのでclose
