### ISSUE TITLE
MPI並列時にpolicyのloadに失敗する

### ISSUE THREAD

**Issue by aoymt** [issp-center-dev/PHYSBO#60]
MPI並列で実行する際に、save で保存した policy を load すると、以下のエラーが出ます。

> Traceback (most recent call last):
>   File "/home/user/work/physbo/work/tutorial3_mpi/run4b.py", line 41, in <module>
>     policy.load(file_history='history.npz', file_training='training.npz', file_predictor='predictor.dump')
>   File "/home/user/.conda/envs/py39-physbo/lib/python3.9/site-packages/physbo/search/discrete/policy.py", line 697, in load
>     self.actions = self._delete_actions(self.history.chosen_actions[:N])
>   File "/home/user/.conda/envs/py39-physbo/lib/python3.9/site-packages/physbo/search/discrete/policy.py", line 798, in _delete_actions
>     return np.delete(actions, index)
>   File "/home/user/.conda/envs/py39-physbo/lib/python3.9/site-packages/numpy/lib/function_base.py", line 5353, in delete
>     keep[obj,] = False
> IndexError: index 9395 is out of bounds for axis 0 with size 5001

読み込み時に、action のリストから既に評価済みの候補を除外する箇所ですが、
リストが分割されている場合に index のエラーになるようです。
修正案を添付します。

[patch.txt](https://github.com/user-attachments/files/16759506/patch.txt)

**Comment by yomichi** [comment]
修正したあと、リリースしようとして忘れていました、すみません。
他のものと合わせてv2.0.2としてリリースしてあります。
