### ISSUE TITLE
初期データ有の多目的ランダム探索におけるエラー

### ISSUE THREAD

**Issue by t-suzuki-jp** [issp-center-dev/PHYSBO#64]
多目的のケースにおいて初期データを読み込ませた状態でランダム探索を行うとエラーが発生します。  

(/physbo/search/discrete_multi/policy.py:154) action = self._get_random_action(N)
(/search/discrete/policy.py:611)     action = self.actions[index]
TypeError: only integer scalar arrays can be converted to a scalar index

self.actionsがリスト型になっていることによるエラーだと思われます。  
physbo/search/discrete_multi/policy.pyのL61の部分をnp.arrayで変換すれば修正可能だと思われますが、変換による影響は不明です。  
（discrete/policy.pyの同じ処理の箇所は、np.arrayで変換処理がされていました）

**Comment by yomichi** [comment]
ありがとうございます、修正しました。
v2.0.2 としてリリースしてあります。
