### ISSUE TITLE
獲得関数値の出力

### ISSUE THREAD

**Issue by takeohoshi** [issp-center-dev/PHYSBO#8]
星健夫(鳥取大)です．
2020年度ISSP高度化プロジェクト(ソフト名：2DMAT)を通じて，PHYSBOを使わせていただいています．ベイズ最適化の途中において，（PHYSBO内部で生成される）獲得関数（全メッシュ上の関数値）の出力ができると良いです．何iterationごとにdumpする，と言うような設定を想定しています．

**Comment by k-yoshimi** [comment]
@takeohoshi 
先日、ver. 1.0をリリースして、獲得関数とガウス過程（事後分布）の期待値と分散を計算できるようにしました。
以下にマニュアルがありますのでご確認ください。
https://issp-center-dev.github.io/PHYSBO/manual/master/ja/notebook/tutorial_basic.html

**Comment by takeohoshi** [comment]
ありがとうございます．見てみます．
